export const BATCH_STATUS = {
  INITIALIZED: 'INITIALIZED',
  IN_TRANSIT: 'IN_TRANSIT',
  DELIVERED: 'DELIVERED',
  OWNED: 'OWNED',
  SOLD: 'SOLD',
  RECALLED: 'RECALLED',
} as const;

export const ORDER_STATUS = {
  PENDING: 'PENDING',
  REQUESTED: 'REQUESTED',
  OFFER_MADE: 'OFFER_MADE',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  FULFILLED: 'FULFILLED',
  ORDERED: 'ORDERED',
} as const;

export const MODAL_TYPE = {
  INFO: 'INFO',
  BATCH_INFO: 'BATCH_INFO',
  ORDER_DETAILS: 'ORDER_DETAILS',
  CREATE_DRUG: 'CREATE_DRUG',
  EDIT_DRUG: 'EDIT_DRUG',
  CREATE_BATCH: 'CREATE_BATCH',
  REQUEST: 'REQUEST',
  OFFER: 'OFFER',
  REJECT: 'REJECT',
  APPROVE_OFFER: 'APPROVE_OFFER',
  FULFILL: 'FULFILL',
  VIEW_FULFILLMENT: 'VIEW_FULFILLMENT',
  RECEIVE: 'RECEIVE',
  TRANSFER: 'TRANSFER',
  SELL: 'SELL',
  HISTORY: 'HISTORY',
  SYNC_ORDER: 'SYNC_ORDER',
  SYNC_BATCH: 'SYNC_BATCH',
} as const;

export const STABLE_BATCH_STATUSES = ['INITIALIZED', 'DELIVERED', 'OWNED'] as const;
